require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

